services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: note_easy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/note_easy?schema=public"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      NEXTAUTH_URL: "http://localhost:3000"
      AUTH_TRUST_HOST: "true"
    ports:
      - "3000:3000"

volumes:
  db_data:
